### ISSUE TITLE
Convert cu8 to Flipper Zero sub format

### ISSUE THREAD

**Issue by strasharo** [rgerganov/spoof_temp#2]
Hello. Sorry for the offtopic question, but do you know by any chance if it's possible to somehow convert the cu8 files produced by rtl_433 to the Flipper Zero .sub format? Thank you.

**Comment by rgerganov** [comment]
The `cu8` file contains raw IQ samples whereas the Flipper's `sub` file contains encoded bit stream. In order to convert `cu8` to `sub`, you need to perform some kind of demodulation. In this particular case the temp station is using ASK/OOK modulated signal, so you need to perform ASK/OOK demodulation.

**Comment by strasharo** [comment]
Thanks for the hint, looks like rtl_443 can demod it with OOK, just need to tweak this one to convert it ot sub I guess.
https://gist.github.com/jinschoi/f39dbd82e4e3d99d32ab6a9b8dfc2f55
